name: Generate Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: serg-backend-developer
          template: classic
          base: header, activity, community
          
      - name: Most used languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: serg-backend-developer
          base: all
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6
