name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: "serg-backend-developer"
          outputs: dist/snake.svg

      - name: Commit and Push the Snake SVG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/snake.svg
          git commit -m "Update snake contribution graph" || echo "No changes to commit"
          git push
