name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: "serg-backend-developer"
          outputs: dist/snake.svg

      - name: Push the Snake SVG to the output branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update snake contribution graph"
          file_pattern: "dist/snake.svg"
